# Generated by Django 4.0.6 on 2022-08-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.CharField(max_length=200)),
                ('ayim_tarihi', models.DateTimeField(verbose_name='yayınlanma tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Secim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secim_metni', models.CharField(max_length=200)),
                ('oylar', models.IntegerField(default=0)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketler.soru')),
            ],
        ),
    ]
